import { StyleSheet } from "react-native";
import { ThemeColors } from "../../../../hooks/useAppTheme";

export const styles = (colors: ThemeColors) =>
  StyleSheet.create({
    pageContainer: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: 50,
    },
    headerWrapper: {
      position: "relative",
      alignItems: "center",
      zIndex: 10,
      paddingHorizontal: 24,
    },
    headerActions: {
      position: "absolute",
      right: 24,
      top: 0,
      bottom: 0,
      flexDirection: "row",
      alignItems: "center",
      zIndex: 20,
    },
    actionButton: {
      padding: 4,
    },
    centerLoading: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingTop: 10,
      paddingBottom: 140,
    },
    summaryCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      paddingTop: 40,
      paddingBottom: 24,
      paddingHorizontal: 24,
      marginBottom: 32,
      shadowColor: colors["brown-dark"],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors["base-card"],
      width: "100%",
      position: "relative",
      overflow: "hidden",
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
    },
    summaryLabel: {
      fontSize: 12,
      color: colors.brown,
      textTransform: "uppercase",
      marginBottom: 4,
      fontWeight: "bold",
      letterSpacing: 0.5,
    },
    salePriceValue: {
      fontSize: 28,
      fontWeight: "bold",
      color: colors["brown-dark"],
    },
    profitValue: {
      fontSize: 28,
      fontWeight: "bold",
    },
    divider: {
      height: 1,
      backgroundColor: colors["base-card"],
      marginVertical: 20,
    },
    costLabel: {
      fontSize: 14,
      color: colors["base-text"],
      opacity: 0.8,
    },
    costValue: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors["base-text"],
    },
    marginBadge: {
      position: "absolute",
      top: 0,
      right: 0,
      borderBottomLeftRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    marginText: {
      color: colors.white,
      fontSize: 12,
      fontWeight: "bold",
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      paddingHorizontal: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors["brown-dark"],
    },
    emptyContainer: {
      padding: 40,
      alignItems: "center",
      justifyContent: "center",
      borderStyle: "dashed",
      borderWidth: 1,
      borderColor: colors.brown,
      borderRadius: 12,
      backgroundColor: colors.white,
      marginTop: 20,
      marginHorizontal: 24,
    },
    emptyText: {
      textAlign: "center",
      color: colors.brown,
      fontSize: 14,
      lineHeight: 20,
    },
    footer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      paddingHorizontal: 24,
      paddingBottom: 40,
      paddingTop: 16,
      backgroundColor: colors.background,
      borderTopWidth: 1,
      borderTopColor: colors["base-card"],
    },
  });
